export const MAX_NUMBER_OF_GUESSES = 11

export const NEW_WORD = 'NEW_WORD'
export const SELECTED_LETTER = 'SELECTED_LETTER'
export const SUBMIT_GUESS = 'SUBMIT_GUESS'
export const GAME_PROGRESS = 'GAME_PROGRESS'
